### ISSUE TITLE
Change colors of titles from JSON config

### ISSUE THREAD

**Issue by reesericci** [deepjyoti30/startpage#12]
Currently I have to go into the CSS to change the title colors if I have custom titles or want the color changed of a default. I think it would be a nice addition if it was possible to change the color of the titles from the JSON config but also have an auto option.
Something like this:
Auto:
```
{
  "name": "title",
  "color": "auto",
   "links" [{}]
},
```
Custom:
```
{
  "name": "title",
  "color": "#FFFFF",
   "links" [{}]
},
```

**Comment by deepjyoti30** [comment]
Yes, I think that's one of the things I will add in the next release along with #8

**Comment by reesericci** [comment]
Cool!

**Comment by reesericci** [comment]
jQuery has a css modifier: https://api.jquery.com/css/

**Comment by deepjyoti30** [comment]
@reesericci I've pushed the changes, try them if you want to and report back in case you face any issues.

**Comment by reesericci** [comment]
Ok will do

**Comment by reesericci** [comment]
I feel like if I say "green" it should pick from a preset green. Or if I say red, pick a preset red. Otherwise, use the hex

**Comment by deepjyoti30** [comment]
@reesericci You mean you want to keep green as a custom variable that should be referenced when you use it??

Why not just use the hex instead??

**Comment by reesericci** [comment]
I want to be able to pick from preset colors. As well as have the option to use a hex.

**Comment by deepjyoti30** [comment]
@reesericci Lemme think what a good way would be to implement that. For now I'm trying to add support for shortcuts from the search bar as requested in #8

**Comment by deepjyoti30** [comment]
@reesericci I think it would be too much of an overhaul to add support to define color variables that can be later referrenced.

Currently, the supported colors are hex and CSS predefined colors.

**Comment by NicTanghe** [comment]
Hex is perfectly fine.

**Comment by reesericci** [comment]
Ok then, closing now
