### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Neules** [deepjyoti30/startpage#13]
Since you have to sign the extension to modify js, it would be nice to have a way (possibly the same as per `--setting`) to edit and translate the strings, as it doesn't have so much strings to translate to be an annoying task.

I mean the month's array and the message's.

Cheers.

**Comment by deepjyoti30** [comment]
Hey @Neules that's sounds like a good feature. I can add an option to select the preferred language and accordingly show the  string. I will look into that.

**Comment by reesericci** [comment]
+1

**Comment by reesericci** [comment]
@deepjyoti30 did you ever look into/add this?

**Comment by deepjyoti30** [comment]
@reesericci Yes I did look into it and it was not possible to add something like that. Google Translate requires a google cloud account with payment setup and other options like yandex aren't free either. I think I should rather accept some help from contributors willing to translate to a certain langauage.

**Comment by reesericci** [comment]
Yeah, that makes sense I guess. Juat have ppl install the google translate extension, that works

**Comment by reesericci** [comment]
Should we close? @deepjyoti30
