### ISSUE TITLE
All values are reseted to defaults on power off

### ISSUE THREAD

**Issue by Neules** [deepjyoti30/startpage#15]
All values are reseted to defaults on power off. What am I doing wrong? Do I need to sign that tedious firefox thing to use it with my links and preferences?

**Comment by deepjyoti30** [comment]
@Neules You won't have to sign it yourself.

I have used it on Firefox myself but hadn't faced that. Let's see if @reesericci has faced it also. He can confirm it I guess.

**Comment by reesericci** [comment]
@Neules Are you running it in temporary mode or getting it from AMO (addons.mozilla.org)?

**Comment by Neules** [comment]
You got the point. I first tried when the project didn't had a AMO page, so you had to do  `about:debugging` on navbar and so on. But without that uninstalled, I installed then the extension by clicking on your AMO, so I guess it got cached or something and it get bugged. 
I deleted the old startpage folder and it's solved now.

**Comment by reesericci** [comment]
Yeah, you have to sign the extension manually if you didn't get from AMO

**Comment by reesericci** [comment]
When you install from about:debugging it only gets installed temporarily. You have to get it signed then  you can install it as a standard extension and it is no longer temporary.

**Comment by reesericci** [comment]
When you restart firefox the extension goes away

**Comment by deepjyoti30** [comment]
Thanks @reesericci for fixing his issue. I thought the issue was existent even with the AMO release. Anyway, Thanks!
