### ISSUE TITLE
Can you add an option to change the time zone?

### ISSUE THREAD

**Issue by ghost** [deepjyoti30/startpage#18]
You should modify the function 'updateTime ()' and add a new variable in the json.

```
this.zone = jsonData["timeZone"] /*"Europe/Madrid"*/
var timeZone = new Date().toLocaleString("en-US", {timeZone: zone});
currentDate = new Date(timeZone);
```

**Comment by deepjyoti30** [comment]
@Walkator I'll take that into consideration. I'm also currently thinking of adding an option to set the preferred language so this will surely go along with that.

**Comment by Walkator** [comment]
Ok, this would be great.

**Comment by reesericci** [comment]
Yeah this ties in with issue #13

**Comment by reesericci** [comment]
@deepjyoti30 dd this get added to manually override the time zone?

**Comment by deepjyoti30** [comment]
@reesericci  Did you check ffe3e6da5c0e78ea7857126d1c9f1ca5ca505d3a

The time zone can be changed from the config.

**Comment by deepjyoti30** [comment]
Added in the last release
