### ISSUE TITLE
Firefox only works on new tab.

### ISSUE THREAD

**Issue by NicTanghe** [deepjyoti30/startpage#19]
Hello so this only works on new tab.
When i open Firefox it's still the same old white background.

**Comment by deepjyoti30** [comment]
@NicTanghe Yes. Firefox has this weird thing that if you open the browser then a new tab is not opened and so the extension is not used either. I did try to check if there's a workaround but didn't find any.

**Comment by reesericci** [comment]
I found a workaround! I'll write up a wiki page for it but here are the steps:
1. Go to this url in firefox: [about:debugging#/runtime/this-firefox](about:debugging#/runtime/this-firefox)
2. find the extension and copy the manifest url
3. Go into the preferences and set the homepage as the manifest url but replace the end of the url with `index.html` instead of `manifest.json`
4. You finished! Now go and test it by opening a new window

**Comment by NicTanghe** [comment]
i`d test if i didn't already just switch to a dracula theme.

**Comment by reesericci** [comment]
Why does that matter?

**Comment by NicTanghe** [comment]
Because my whole desktop ect is now dracula themed.
If i could edit the config in the right cick menu to change the color sheme id test it :D  

PLz update description tho. (possibly integrate in addon.)

**Comment by reesericci** [comment]
If you manually build & sign the extension you can edit the CSS. That's what I did.

**Comment by deepjyoti30** [comment]
@NicTanghe I'll add theming options in the next release, a lot of requests for those.! @reesericci Thanks for the solution!

**Comment by reesericci** [comment]
The theming goes along with issue #12

**Comment by reesericci** [comment]
@deepjyoti30 can you put my solution into the wiki?

**Comment by reesericci** [comment]
and double check it :)

**Comment by deepjyoti30** [comment]
@reesericci Added that.

**Comment by NicTanghe** [comment]
(i know it's irrelevant to this feature request but does anyone know if this website works with vimium? My current newtab extension does not)

**Comment by deepjyoti30** [comment]
@NicTanghe I'm afraid you're gonna have to test it out yourself. I'm not an avid firefox user or I could've tried it out.

Also as of now, I'm adding some neat features like suggestions as you type on the search bar.

**Comment by NicTanghe** [comment]
Have you added the eazy theming yet ?
if u did i wil test this out and report back to you.

**Comment by deepjyoti30** [comment]
@NicTanghe In terms of theming, the colors in the squares can be changed as of now. Other than that if you have any extra theming related suggestions, you can always open a feature request.

**Comment by reesericci** [comment]
Ok closing

**Comment by reesericci** [comment]
Or not

**Comment by reesericci** [comment]
@NicTanghe opened this one

**Comment by deepjyoti30** [comment]
Yeah. I'll close this once I make the next release or @NicTanghe  can close as he wishes

**Comment by NicTanghe** [comment]
On next release I'll test if the fix works if it doesn't work I'll let you
know.

**Comment by reesericci** [comment]
I use the fix on my firefox

**Comment by reesericci** [comment]
@deepjyoti30 can you make the wiki community-editable? The fix is for opening on new windows.

**Comment by reesericci** [comment]
I also found an easier way:

1. Open a **new** firefox window, and go to about:preferences
2. Open a new tab, and make sure that minimal-startpage is open and is the only other tab
3. In preferences go to "Home" in the sidebar
4. Under Homepage & new windows select "Custom URLs..."
5. Click "Use Current Pages"
Done!

**Comment by deepjyoti30** [comment]
@reesericci Thanks for that. I will update the Wiki with this way also.

**Comment by reesericci** [comment]
@NicTanghe close

**Comment by deepjyoti30** [comment]
Added in the Wiki
