### ISSUE TITLE
Change Info On Page?

### ISSUE THREAD

**Issue by iisGmoney** [deepjyoti30/startpage#2]
How Do I Change The Info On The New Tab

**Comment by deepjyoti30** [comment]
Do you mean the message gretting the user??

It changes based on time automatically.

**Comment by iisGmoney** [comment]
I want to know how to change the username and websites, I changed the username and links, and the names of one of the categories and it dissapeared.
![config](https://user-images.githubusercontent.com/59393872/81844618-f7f2f200-9514-11ea-8368-75f69af2bccc.png)
![new_tab](https://user-images.githubusercontent.com/59393872/81844638-ff1a0000-9514-11ea-9c29-ef5de544c2be.png)

**Comment by iisGmoney** [comment]
It also bricks the google search bar.

**Comment by haideralipunjabi** [comment]
You should have pasted the code as text. The image makes it difficult to debug.

I think you should try removing the commas `,` at the end of line 12 & line 26.

**Comment by deepjyoti30** [comment]
@iisGmoney Can you also check if there are errors thrown by JS?

Just open developer tools using ```Ctrl+Shift+i``` and check the console.

**Comment by iisGmoney** [comment]
Yup, index.html:1 Uncaught (in promise) SyntaxError: Unexpected token ] in JSON index.html : 1 at position 538.

**Comment by deepjyoti30** [comment]
Make the changes as suggested by @haideralipunjabi , the issue is because of those extra commas.

**Comment by iisGmoney** [comment]
Thanks
