### ISSUE TITLE
Firefox --setting just searches for settings.

### ISSUE THREAD

**Issue by NicTanghe** [deepjyoti30/startpage#20]
Firefox --setting just searches for settings.

So i can't change the settings and being greeted as someone i'm not is quite annoying.

Maybe just ad a config in the extension settings menu like vim vixen.

**Comment by deepjyoti30** [comment]
@NicTanghe I just tried it right now and it did open the settings.

Are you sure you are using the latest release?? Get the latest one from AMO and install it, then check.

**Comment by reesericci** [comment]
Works fine for me. Make sure you're typing in the search bar on the startpage and not the omnibar up at the top.

**Comment by reesericci** [comment]
@NicTanghe is this still an issue? Please close if finished

**Comment by reesericci** [comment]
@deepjyoti30 Assume resolved, please close this issue
