### ISSUE TITLE
Not a prob with the extention, just a prob with the Wiki

### ISSUE THREAD

**Issue by iisGmoney** [deepjyoti30/startpage#23]
When I try installing the npm thing that I need to download I get this error.

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/web-extension - Not found
npm ERR! 404
npm ERR! 404  'web-extension@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Thanks in advance

**Comment by deepjyoti30** [comment]
@iisGmoney Sorry about that, turns out it's a typo.

You need to install ```web-ext``` instead of ```web-extension```.

Do this instead:

```console
npm install -g web-ext
```

**Comment by iisGmoney** [comment]
Thanks

**Comment by iisGmoney** [comment]
Also, on the place where I'm supposed to click "Distribute My Own" there is no button
![cantselectdistributemyown](https://user-images.githubusercontent.com/59393872/83899977-ef11cc80-a71e-11ea-9446-fc5a92cc7224.png)

**Comment by iisGmoney** [comment]
Actually I figured out where to go.

**Comment by reesericci** [comment]
Sorry, it seems you skipped a step

**Comment by reesericci** [comment]
Whoops not in the wiki page. @deepjyoti30 can you update with a step that says 

1. Click "Submit Your First Addon" 


before the first step in Signing the Built Extension
