### ISSUE TITLE
Wiki is not community-editable

### ISSUE THREAD

**Issue by reesericci** [deepjyoti30/startpage#31]
I can't submit changes to the the wiki.

https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

**Comment by deepjyoti30** [comment]
@reesericci I can enable access, however are you aware if users will get direct write access? Or will it be like PR's? Like I would have to verify before allowing changes.

**Comment by reesericci** [comment]
I'm not sure, you will have to look into that. maybe change it to be all MD documents? that way it will all be PR-able

**Comment by deepjyoti30** [comment]
@reesericci I have made it community editable. Try making some small change so that I can know if it still needs my permission to publish the changes.

**Comment by reesericci** [comment]
It does not need permission to change but I can see all the revisions.

**Comment by deepjyoti30** [comment]
@reesericci Feel free to close this since the WiKi is now community editable.
