### ISSUE TITLE
Make section titles clickable

### ISSUE THREAD

**Issue by reesericci** [deepjyoti30/startpage#32]
It would be cool If I could click the titles of the sections to go to a website

**Comment by deepjyoti30** [comment]
@reesericci You mean clicking on the card title? I just feel like it would be a bit redundant to do that.

**Comment by reesericci** [comment]
Let's say I have a main page, and I can have the card title go to that main page.

**Comment by deepjyoti30** [comment]
@reesericci All right, lemme see if it will be possible to add that functionality without breaking anything.

**Comment by deepjyoti30** [comment]
@reesericci  Should be added in dc818bd2b588987028

Do give it a try. I will udpate the WiKi soon. In order to make the titles clicable, you need to add a `url` attribute to the `square` object in the config.

**Comment by reesericci** [comment]
great!
