### ISSUE TITLE
Add manifest.json to release zip

### ISSUE THREAD

**Issue by reesericci** [deepjyoti30/startpage#34]
Add a manifest.json for firefox in the release zip for easy uploading to addons.mozilla.org to remove the step of building.

**Comment by reesericci** [comment]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/19589006/104817112-ddc88c80-57e4-11eb-8027-8ed094923943.png">

**Comment by reesericci** [comment]
I think you will have to do the web-ext building per release to generate this manifest.json

**Comment by deepjyoti30** [comment]
@reesericci Just checked. The issue was that in the latest release, I zipped the directory of startpage and not just the contents. I'll update the release files.

**Comment by deepjyoti30** [comment]
@reesericci Updated the release!

**Comment by reesericci** [comment]
one sec lemme try it

**Comment by reesericci** [comment]
I just downloaded the september release and getting the same error. Try running `web-ext build` on the zip and uploading the zip that it creates into the release.

**Comment by reesericci** [comment]
@deepjyoti30

**Comment by deepjyoti30** [comment]
@reesericci I see, the issue was at my end. I updated the zip. It should work now!

**Comment by reesericci** [comment]
It worked! Updated the wiki
