### ISSUE TITLE
Build xpi at time of release

### ISSUE THREAD

**Issue by reesericci** [deepjyoti30/startpage#39]
that way the end user can skip the building step and only have to upload the finished xpi to mozilla.

**Comment by reesericci** [comment]
whoops i forgot that you upload a zip to amo not an xpi

**Comment by deepjyoti30** [comment]
@reesericci I think though that a zip can be built using GitHub Actions, sounds like a good option.

**Comment by deepjyoti30** [comment]
@reesericci I think the zip I was providing with each release is not important anymore since it can be directly installed by cloning the repo. 

I'll update the installation instructions and move to `download latest release source zip` rather than attaching a build during release.

**Comment by reesericci** [comment]
> @reesericci I think the zip I was providing with each release is not important anymore since it can be directly installed by cloning the repo.
> 
> I'll update the installation instructions and move to `download latest release source zip` rather than attaching a build during release.

just make sure it has the manifest.json so we don't have issue #34 come up again.

**Comment by deepjyoti30** [comment]
@reesericci As in the latest release, I have not added any custom zip. It's just the one provided by GitHub which has the source code as of the release date. That one surely contains the `mainfest.json` file because the source contains it, so should be cool!
