### ISSUE TITLE
Customize the title

### ISSUE THREAD

**Issue by mohkale** [deepjyoti30/startpage#40]
I'm not a big fan of lower-case titles. It'd be nice if you could customize the start-page title from the config file.

**Comment by deepjyoti30** [comment]
@mohkale You can directly change the titles of the squares from the config itself.

Just open settings and change it according to your needs. Does that not suit your needs?

**Comment by mohkale** [comment]
@deepjyoti30 

Sorry, not the squares, the HTML page. So the contents of the ~<title></title>~ element.

**Comment by deepjyoti30** [comment]
@mohkale I know it's late but I finally added this feature. If you're still interested you can take a look at the latest commits of the `dev` branch. I will make a release soon!

**Comment by mohkale** [comment]
Fantastic, thanks :-).

**Comment by deepjyoti30** [comment]
@mohkale The feature is now available in the latest release!
