### ISSUE TITLE
Hosting on nginx?

### ISSUE THREAD

**Issue by rwjack** [deepjyoti30/startpage#41]
Hi, is hosting this on nginx possible?

![image](https://user-images.githubusercontent.com/59068073/145820345-5d3ba86d-22ae-4aef-9f76-19a899b95c8d.png)

This is all I get.

**Comment by deepjyoti30** [comment]
@cysea It should be possible. However there might be some changes required. The main purpose of the app is to work as a browser extension so it might not work with nginx right away.

Could you share the logs from developer tools? Looking at the image above there should be some error. Looks like the JS is not loaded properly.
