### ISSUE TITLE
Opening a link in a new tab

### ISSUE THREAD

**Issue by JoshFink** [deepjyoti30/startpage#42]
Hi, is it possible to open a link, when clicked, in a new tab. 

Thanks

**Comment by deepjyoti30** [comment]
It's not possible till now. I can consider adding that feature though, considering at this point we support quicklinks that would be a nice feature!

**Comment by JoshFink** [comment]
Thanks

**Comment by deepjyoti30** [comment]
Added in the latest release, refer to docs to understand how to use it: https://github.com/deepjyoti30/startpage/wiki/Configuration
