### ISSUE TITLE
Is there a way to backup and restore the configuration

### ISSUE THREAD

**Issue by JoshFink** [deepjyoti30/startpage#43]
After spending some time to put in everything I'm wondering if I'm missing a away to back up the configuration so that in case something crashes I can restore it. 

If someone could point me in the right direction I would appreciate it. 

Thanks

**Comment by deepjyoti30** [comment]
Currently there's no such way provided by the extension itself.

However, considering the extension can be installed from an unpacked directory, the default config is located in that directory.

So you can make changes to that config directly and try reloading the page, I think startpage would pick up the changes.

That just means you can basically backup the config from the directory where you unpacked the extension and then put it in any other device (where the extension is unpacked) and it will work like the way you want it to.

**Comment by JoshFink** [comment]
Thanks.. I'll try that. If I had to reconfigure this after setting it up it would definitely promote me to find something else. So far I'm really liking it.

**Comment by deepjyoti30** [comment]
@JoshFink The import/export button support is added in this commit: [0f6573f](https://github.com/deepjyoti30/startpage/commit/0f6573f451261e4386661040aebe21035758bf85). You can try it out if you want.

The feature will be live soon in the next release along with some other useful new features!

**Comment by deepjyoti30** [comment]
@JoshFink The feature is now live at: https://github.com/deepjyoti30/startpage/releases/tag/1.1
