### ISSUE TITLE
Link Coloring

### ISSUE THREAD

**Issue by rahaaatul** [deepjyoti30/startpage#46]
Is it possible to color the links inside squares, individually? If so, how to do them?

I tried duplicating color and inserting in one of the links but it doesn't work.

**Comment by deepjyoti30** [comment]
@rahaaatul It is not supported on a per link basis.

See the theme is defined in the way that the color will be set for the title of the square and the links will show the same color when hovered on.

**Comment by deepjyoti30** [comment]
Will add this as a feature in the next release. If color would be defined for a link, it would be prioritized over the square color.

**Comment by rahaaatul** [comment]
> Will add this as a feature in the next release.
Awesome! 😊

> If color would be defined for a link, it would be prioritized over the square color.
I agree. 👍

**Comment by deepjyoti30** [comment]
Added in the latest release
