### ISSUE TITLE
Time is not correct. (GMT Timezone)

### ISSUE THREAD

**Issue by j-koziel** [deepjyoti30/startpage#50]
The time here in the UK went an hour forward however this has not been adjusted in the start page. I've tried re-building multiple times but to no avail. Is there a way to fix this.

This is the time in the start page.
![image](https://user-images.githubusercontent.com/68497216/168463390-0db90cbb-7ff7-4456-a3b4-301dca1c8599.png)

This is the correct time.
![image](https://user-images.githubusercontent.com/68497216/168463398-3d91e0cb-51cf-4833-8be0-2a256e9730fc.png)

**Comment by j-koziel** [comment]
`"title": "home",
  "searchEngine": "Google",
  "user": "Jonathan",
  "disableMessage": false,
  "disableDate": false,
  "disableSearchBar": false,
  "disable24Hour": false,
  "disableWeather": false,
  "timeZone": "GMT",
  "weatherConf": {
    "location": "London United Kingdom",
    "unit": "cel"
  },
  "settingsIcon": false,
  "style": {
    "backgroundColor": "#282828",
    "messageColor": "#fbf1c7",
    "dateColor": "#ebdbb2",
    "lineColor": "#fbf1c7",
    "weatherColor": "#ebdbb2",
    "searchColor": "#fbf1c7",
    "searchBackgroundColor": "#3c3836",
    "squareColor": "#a89984",
    "squareBackgroundColor": "#3c3836",
    "autocompleteHighlightBackgroundColor": "#504945"
  },
  "quickLinks": {
    "r": "https://reddit.com",
    "g": "https://github.com",
    "y": "https://youtube.com"
  }
}
`

**Comment by deepjyoti30** [comment]
@j-koziel I just tried reproducing the issue locally with fail.

Here's what I did:

1. Set the `timeZone` field in the config as `GMT`: Time showed up as `15:00`.
2. I then google `GMT time right now` and got the result as `15:00`.

What am I missing here?

**Comment by j-koziel** [comment]
My config is set to GMT but I'm not getting the right time. I've tried rebuilding multiple times but it still doesn't work :(

**Comment by j-koziel** [comment]
Ok I've spotted the error. I'm using the wrong time zone :D. Sorry for the bother.
