### ISSUE TITLE
Support for Kiwi Browser

### ISSUE THREAD

**Issue by rahaaatul** [deepjyoti30/startpage#52]
Can you add support for Kiwi Browser? It's an Android browser supports chromium extensions. I installed it in the browser but it's act and looks weird, so for now I'm using just one square.

![Screenshot_20220724_235148](https://user-images.githubusercontent.com/86149861/180661158-89738f49-7ea0-4d4f-bb71-d9761cc7510a.jpg)

Btw, how do we change the square to rectangle? I'm trying to put all of them in one square. I did this and the greeting message went up under toolbar and can't scroll it back to visibility.

![Screenshot_20220725_004223](https://user-images.githubusercontent.com/86149861/180661403-6324a61a-f87d-4362-b4c1-7acbac3ac4ef.jpg)
 How do I add two squares side by side and fit it in the browser?

**Comment by deepjyoti30** [comment]
The thing is UI is not responsive for mobile devices. It's not a browser specific issue, instead the page is not responding to the smaller screen size.

I will try to fix this as much as possible but there might be issues supporting multiple squares and might break the overall design language of `startpage` in which case I cannot guarantee that you would love using it 😅 .

**Comment by rahaaatul** [comment]
> The thing is UI is not responsive for mobile devices. It's not a browser specific issue, instead the page is not responding to the smaller screen size.
> 
> I will try to fix this as much as possible but there might be issues supporting multiple squares and might break the overall design language of `startpage` in which case I cannot guarantee that you would love using it 😅 .

How about another repo just for Mobile Devices? I understand if you don't agree, it's time consuming and waste of time to develop just for one user 😅.

If it might break something, you should ignore this issue then.
