### ISSUE TITLE
When the window is small the message is cut off.

### ISSUE THREAD

**Issue by anchovyyy** [deepjyoti30/startpage#53]
Screenshot:

![image](https://user-images.githubusercontent.com/98144599/193386767-083a2e2b-5ae8-4bd6-aa75-5b2c6374657a.png)

Normally:

![image](https://user-images.githubusercontent.com/98144599/193386781-9af1673c-d152-4e3d-9f76-f72c93099ed8.png)

Also I'm pretty sure that "It's too late, take some sleep!" is grammatically incorrect, It should be: "It's really late, get some sleep!"

**Comment by deepjyoti30** [comment]
@anchovyyy Thanks for pointing out the issue with the message being cut off. Will check if it will be possible to add a fix. Can you tell me where exactly you used the startpage with such a small window? Was it a VM?

**Comment by anchovyyy** [comment]
I use bspwm with pretty large gaps (20 px).

![image](https://user-images.githubusercontent.com/98144599/194942691-0483cd82-801d-42b3-a37f-d9c9d21b7cce.png)

**Comment by anchovyyy** [comment]
I use bpswm with pretty large gaps (20px)

![image](https://user-images.githubusercontent.com/98144599/194943115-296c7d70-d35c-48ad-8f17-8c8c57d4bdf3.png)

**Comment by deepjyoti30** [comment]
@anchovyyy The [bae77b3](https://github.com/deepjyoti30/startpage/commit/bae77b33b4ecc893ce814e28bd77aebfbb711ba1) PR fixes the issue. If you want, you can test out the commit and report here if it does not fix your issue.

I have tested it on my end and it does fix the issue.

**Comment by deepjyoti30** [comment]
@anchovyyy Fix is now live with `v1.1`. You can check it here: https://github.com/deepjyoti30/startpage/releases/tag/1.1

I am closing the issue.
