### ISSUE TITLE
Manifest version 2 is deprecated, and support will be removed in 2023.

### ISSUE THREAD

**Issue by Severrinn** [deepjyoti30/startpage#55]
Hi there, 
I saw this error while installing the extension on Chrome. Will this be an issue or resolved for the new year? Thanks!

Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

<img width="879" alt="image" src="https://user-images.githubusercontent.com/64810167/209230120-a44c5ac5-76c1-4f4c-a55d-6229154af596.png">

**Comment by deepjyoti30** [comment]
Hey @Severrinn thanks for bringing this to my attention. I was not aware of this error. I have just fixed the issue, I will make a release so that this error won't happen again.

You can test the latest commits from `master` and let me know if the issue happens again.

**Comment by Severrinn** [comment]
@deepjyoti30  Looks good with the new update.
