### ISSUE TITLE
The addon failed to meet requirement of manifest version 3 and above

### ISSUE THREAD

**Issue by redve-dev** [deepjyoti30/startpage#56]
I have just cloned the repo, followed the instruction of building and signing the addon. I see there is manifest in version 3 in manifest.json, however mozilla portal doesn't recognize it.
I have built it with latest version of web-ext, on arch linux with latest zen kernel.
![image](https://user-images.githubusercontent.com/106469071/213935364-51538ce7-9dff-47d0-aeb4-fd1c3f6b0492.png)

**Comment by deepjyoti30** [comment]
@redve-dev Thanks for pointing this out. Just updated the release and the issue is fixed!
