### ISSUE TITLE
Run on a server

### ISSUE THREAD

**Issue by landcraft** [deepjyoti30/startpage#57]
how to host this on a server as a site, rather than as a local extension? I've tried to publish to cloudflare pages, but I get nothing coming up, except Good Morning | Fetchig Weather.
Is it possible to use Cloudflare workers to somehow make it work?

**Comment by deepjyoti30** [comment]
Not sure if you'd be able to use cloudfare workers. Since the project is built as an extension.

Have you tried taking the whole directory and hosting it locally? If that works then that means you will be able to host it as a static website.
