### ISSUE TITLE
Not able to build/sign 

### ISSUE THREAD

**Issue by Syddii** [deepjyoti30/startpage#60]
Hey, first of all I'm not the smartest so I'm so sorry if there's something I'm missing/doing wrong!!
I've downloaded latest repo & am following instructions on "Firefox Building & Signing" - in Mozilla Developer Hub went to "Submit your First Addon", distribute my own, selected compatibility for both Firefox & Firefox for Android, selected the file (zip), but..
Developer Hub is just throwing: 
"Your add-on failed validation with 1 error.
    manifest.json was not found"
I've downloaded v1.1 and (just in case lol) also tried with v0.5, but am still getting the same issue - Is there something I'm doing wrong here? Someone pls help

**Comment by deepjyoti30** [comment]
@Syddii Can you confirm if this step worked correctly for you before you uploaded the zip on mozilla?

`web-ext build`

Did you follow [these steps](https://github.com/deepjyoti30/startpage/wiki/How-to-sign-the-extension-for-Personal-Use-on-Firefox) before submitting?

**Comment by Syddii** [comment]
@deepjyoti30 Kia ora,
Thank you so much for responding - I'm very sorry as didn't see this until now!
Those are the steps that I followed, I did not follow step one as I was not making any changes to the code, is this where I went wrong?
Apologies for any obvious questions as I'm not a very techy person kek

**Comment by deepjyoti30** [comment]
Yeah, that is a step that you cannot skip. Try following all the steps and you can report back here if it still doesn't work.
