### ISSUE TITLE
Weather?

### ISSUE THREAD

**Issue by reesericci** [deepjyoti30/startpage#7]
Would it be possible to use something like the Dark Sky API to grab weather information and display it on the startpage like this (with correct font/font size)?

![Weather UI](https://user-images.githubusercontent.com/19589006/82058214-0d3d5d00-968a-11ea-8014-7556879cd349.png)

**Comment by deepjyoti30** [comment]
Hey @reesericci , I can work on adding weather but i think using Dark Sky's API won't be the way to go since their API will probably become private in a few monts, I'll check other API's and add the feature soon.

**Comment by reesericci** [comment]
I'm just using dark sky as an example but you could use any weather provider. Thanks for considering my idea!

**Comment by deepjyoti30** [comment]
@reesericci Added weather in 501cb6d

Test it, report here if you find any bug.

**Comment by reesericci** [comment]
Liking it! (Had to do some git rebasing to install it though - no problems) Although, I'd like it if the weather was rounded instead of having numbers like 81.97 degrees and would rather it say 82 degrees or whatever. Otherwise, no complaints!

**Comment by deepjyoti30** [comment]
@reesericci I think it makes sense to round the weather, I thought showing it to 2 values would be good.

**Comment by reesericci** [comment]
@deepjyoti30 I think it looks cleaner without the decimals but either way is perfectly fine! (I'm currently packaging and signing the startpage so I don't have to keep re-installing it in firefox!)

**Comment by deepjyoti30** [comment]
@reesericci I already pushed a change to make it integer.

About Firefox, I know that we need to sign them individually and only then install. I thought I would sign one and share a release but the thing is the config cannot be edited so that would mean the user would be stuck with the default config which I don't want.

It's way simpler for Chrome though.

**Comment by reesericci** [comment]
Thanks for the weather!
Also, here's an idea: popup a json editor when you hit a hotkey instead of making a gui, so you can package for firefox/chrome. (I really don't know how hard that would be though)

**Comment by deepjyoti30** [comment]
@reesericci I've been thinking the same thing, that rather than adding a GUI which will indirectly edit the json, I can just let the users directly edit the json from a popup editor, let's see.

**Comment by reesericci** [comment]
You should add a variable to enable/disable weather like 24hr time,etc

**Comment by reesericci** [comment]
All weather functionality has been added, closing issue.
