### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by oberprah** [deepjyoti30/startpage#8]
I really like this project, it looks great.

But for me it is a bit annoying to use the mouse to select one of the links. It would be very cool to select them with a shortcut or by using a text field with autocompletion.

**Comment by reesericci** [comment]
I like this idea possibly. Leaning more towards the autocomplete side of things though. Could you implement this possibly @deepjyoti30 ?

**Comment by deepjyoti30** [comment]
@oberprah You can always use the tab to select the URL's, did you try that.

The first tab will get you on the search bar and after that you will be able to browse through the URL's with each tab. Finally entering will open that URL.

**Comment by oberprah** [comment]
@deepjyoti30 yes, that could be a workaround, but not exactly what I need. If I have 20 URLs, then I have to click on tab 20 times.

**Comment by reesericci** [comment]
Something like duckduckgo bangs to quickly open urls with a custom prefix and custom "tag" for each url. Like YouTube could have the tag "yt" and i would type into the searchbar "--yt" and it would take me to YouTube.

**Comment by deepjyoti30** [comment]
@reesericci @oberprah Hey guys, I have kind of added the feature. It still needs some fixes but I would be glad if you guys could try it out and give your inputs on how it looks etc.

**Comment by oberprah** [comment]
Currently, it seems a little buggy, but it is a very nice feature. Thanks!

**Comment by deepjyoti30** [comment]
@oberprah Yeah I know it is a bit buggy at the moment. Glad that you like it!

**Comment by deepjyoti30** [comment]
@oberprah The bug is now fixed. You can try it out and report back here if you want. If everything is fine I will probably be doing a release soon.

**Comment by oberprah** [comment]
@deepjyoti30 perfect, I really like it, thanks!

**Comment by reesericci** [comment]
@deepjyoti30 How does the feature work?

**Comment by deepjyoti30** [comment]
@reesericci As you start typing on the search bar it will start showing you suggestions, that can be clicked on. You can just try out the latest commits.

**Comment by reesericci** [comment]
Ooh nice, gonna build soon

**Comment by deepjyoti30** [comment]
@reesericci It already does that. When you click on any suggestion, it actually open up that URL.

In terms of making it an option, I think I can surely do that.

**Comment by reesericci** [comment]
No it doesn't here's a gif:

![startpage](https://user-images.githubusercontent.com/19589006/92110905-107f6480-edb1-11ea-8a81-70050bc50b4a.gif)

**Comment by deepjyoti30** [comment]
@reesericci Okay I got it. You meant when there is a mouse click you want it to go to that site. Currently, if you click enter on the selected suggestion it'll go to that site but I'll consider taking a look to see why it's not doing the same for mouse clicks.

**Comment by deepjyoti30** [comment]
Added in the last release
