### ISSUE TITLE
Wiki page for Firefox building & signing

### ISSUE THREAD

**Issue by reesericci** [deepjyoti30/startpage#9]
Could you enable the wiki so I could submit a page for building and signing the extension for Firefox so the extension is not loaded temporarily?

**Comment by deepjyoti30** [comment]
Hey @reesericci I enabled the Wiki yesterday itself. Anyway, I added a settings menu on the extension and I'm thinking of pushing it to the respective add on stores.

If you want, try it out and raise an issue if you find any bugs.

**Comment by reesericci** [comment]
I just finished writing up the wiki page but GH doesn't support pull requests on wiki pages so here's the page for you to create:

## Firefox Building & Signing

To make the startpage extension permanent and not have to re-add the extension every time you restart Firefox, you must build the extension/your config and get it signed by Mozilla.

### Building the extension

Install node.js/npm from [nodejs.org](https://nodejs.org) so we can install the web-ext tools.

To install the web-ext tools so we can build the extension, run this command in a terminal after installing npm:

```
npm install -g web-extension
```
Then change directory into the same directory as the startpage extension files. Example: ```cd startpage```
Then use web-ext to build the extension:

```
web-ext builds
```
This will create a directory called web-ext-artifacts and in which there will be a zip file. This file is your built extension.

### Signing the built extension

To get the extension signed by Mozilla you have to go to the [Mozilla Developer Hub](https://addons.mozilla.org/en-US/developers/) and sign in with a Firefox Account.

Select "Distribute on my own"

Then click "Upload File" and select the startpage directory, then web-ext-artifacts, then the zip file that was just created.

Then select compatibility with Firefox and Firefox for Android

Then hit "Sign add-on", Click "No" for source-code distribution and then wait 5-10 minutes.

### Downloading the signed extension

Once you've waited 5-10 minutes your extension should have been signed.

To download the extension go to the Developer Hub and click the button that says "View All Submissions"

Then click "minimal-startpage"

Then on the left sidebar click "Manage Status & Versions"

##### Tip: To update the extension  change the extension's version number in manifest.json, build the extension, and then click "Upload a new version" on this page, then follow the steps below.

Then in the top version number's section check the "Status" if it says "Approved" then you are good to go!

Then click the top version number

Then under files, click the .xpi file and install it!

### You're done!

**Comment by reesericci** [comment]
Also, settings menu works great although the UI color scheme could be improved if possible, as well as making it --settings instead of --setting. Otherwise, works great!

**Comment by deepjyoti30** [comment]
@reesericci Can you directly gimme the markdown for the wiki page. It'd be easier for me to just copy paste.

**Comment by reesericci** [comment]
`## Firefox Building & Signing

To make the startpage extension permanent and not have to re-add the extension every time you restart Firefox, you must build the extension/your config and get it signed by Mozilla.

### Building the extension

Install node.js/npm from [nodejs.org](https://nodejs.org) so we can install the web-ext tools.

To install the web-ext tools so we can build the extension, run this command in a terminal after installing npm:

```
npm install -g web-extension
```
Then change directory into the same directory as the startpage extension files. Example: ```cd startpage```
Then use web-ext to build the extension:

```
web-ext builds
```
This will create a directory called web-ext-artifacts and in which there will be a zip file. This file is your built extension.

### Signing the built extension

To get the extension signed by Mozilla you have to go to the [Mozilla Developer Hub](https://addons.mozilla.org/en-US/developers/) and sign in with a Firefox Account.

Select "Distribute on my own"

Then click "Upload File" and select the startpage directory, then web-ext-artifacts, then the zip file that was just created.

Then select compatibility with Firefox and Firefox for Android

Then hit "Sign add-on", Click "No" for source-code distribution and then wait 5-10 minutes.

### Downloading the signed extension

Once you've waited 5-10 minutes your extension should have been signed.

To download the extension go to the Developer Hub and click the button that says "View All Submissions"

Then click "minimal-startpage"

Then on the left sidebar click "Manage Status & Versions"

##### Tip: To update the extension  change the extension's version number in manifest.json, build the extension, and then click "Upload a new version" on this page, then follow the steps below.

Then in the top version number's section check the "Status" if it says "Approved" then you are good to go!

Then click the top version number

Then under files, click the .xpi file and install it!

### You're done!
`

**Comment by reesericci** [comment]
```
## Firefox Building & Signing

To make the startpage extension permanent and not have to re-add the extension every time you restart Firefox, you must build the extension/your config and get it signed by Mozilla.

### Building the extension

Install node.js/npm from [nodejs.org](https://nodejs.org) so we can install the web-ext tools.

To install the web-ext tools so we can build the extension, run this command in a terminal after installing npm:

```
npm install -g web-extension
```
Then change directory into the same directory as the startpage extension files. Example: ```cd startpage```
Then use web-ext to build the extension:

```
web-ext builds
```
This will create a directory called web-ext-artifacts and in which there will be a zip file. This file is your built extension.

### Signing the built extension

To get the extension signed by Mozilla you have to go to the [Mozilla Developer Hub](https://addons.mozilla.org/en-US/developers/) and sign in with a Firefox Account.

Select "Distribute on my own"

Then click "Upload File" and select the startpage directory, then web-ext-artifacts, then the zip file that was just created.

Then select compatibility with Firefox and Firefox for Android

Then hit "Sign add-on", Click "No" for source-code distribution and then wait 5-10 minutes.

### Downloading the signed extension

Once you've waited 5-10 minutes your extension should have been signed.

To download the extension go to the Developer Hub and click the button that says "View All Submissions"

Then click "minimal-startpage"

Then on the left sidebar click "Manage Status & Versions"

##### Tip: To update the extension  change the extension's version number in manifest.json, build the extension, and then click "Upload a new version" on this page, then follow the steps below.

Then in the top version number's section check the "Status" if it says "Approved" then you are good to go!

Then click the top version number

Then under files, click the .xpi file and install it!

### You're done!
```

**Comment by reesericci** [comment]
Here you go: https://hastebin.com/raw/wekunaxecu

**Comment by deepjyoti30** [comment]
@reesericci Thank's for that.

I updated the Wiki and the Readme and also added at the end of the Wiki that it was written by you. Thanks again.

**Comment by reesericci** [comment]
No problem. Closing Issue
